export interface MenuItem {
  id: string;
  code: string;
  title: string;
  hasChildren?: boolean;
  icon?: string;
  shortcut?: string;
  actionUrl?: string;
  children?: MenuItem[];
}

export const WBASE_MENU_DATA: MenuItem[] = [
  {
    id: 'cat_100',
    code: '100',
    title: '事務所資料',
    hasChildren: true,
    icon: 'Building2',
    children: [
      {
        id: 'm_110',
        code: 'wbase1010',
        title: '事務所資料',
        hasChildren: false,
        actionUrl: '/wbase/wbase1010',
      },
      {
        id: 'm_120',
        code: 'wbase1020',
        title: '會計師/記帳士資料',
        hasChildren: false,
        actionUrl: '/wbase/wbase1020',
      },
      {
        id: 'm_130',
        code: 'wbase1030',
        title: '員工資料',
        hasChildren: false,
        actionUrl: '/wbase/wbase1030',
      },
      {
        id: 'm_140',
        code: 'wbase1040',
        title: '密碼群組',
        hasChildren: false,
        actionUrl: '/wbase/wbase1040',
      },
      {
        id: 'm_150',
        code: 'wbase1050',
        title: '稅務人員',
        hasChildren: false,
        actionUrl: '/wbase/wbase1050',
      },
      {
        id: 'm_160',
        code: 'wbase1060',
        title: '收費項目',
        hasChildren: false,
        actionUrl: '/wbase/wbase1060',
      },
      {
        id: 'm_170',
        code: 'wbase1070',
        title: '備註',
        hasChildren: false,
        actionUrl: '/wbase/wbase1070',
      },
      {
        id: 'm_180',
        code: 'wbase1080',
        title: '摘要',
        hasChildren: false,
        actionUrl: '/wbase/wbase1080',
      },
    ],
  },
  {
    id: 'cat_200',
    code: '200',
    title: '客戶資料',
    hasChildren: true,
    icon: 'Users',
    children: [
      {
        id: 'm_210',
        code: 'wbase2010',
        title: '客戶資料建檔',
        hasChildren: false,
        actionUrl: '/wbase/wbase2010',
      },
      {
        id: 'm_215',
        code: 'wbase2010_split',
        title: '客戶資料建檔 (左右雙欄測試)',
        hasChildren: false,
        actionUrl: '/wbase/wbase2010_split',
      },
      {
        id: 'm_220',
        code: 'wbase2020',
        title: '客戶資料匯出',
        hasChildren: false,
        actionUrl: '/wbase/wbase2020',
      },
      {
        id: 'm_230',
        code: 'wbase2030',
        title: '客戶資料匯入',
        hasChildren: false,
        actionUrl: '/wbase/wbase2030',
      },
      {
        id: 'm_240',
        code: 'wbase2040',
        title: '客戶收費資料輸入',
        hasChildren: false,
        actionUrl: '/wbase/wbase2040',
      },
      {
        id: 'm_250',
        code: 'wbase2050',
        title: '總分支機構設定',
        hasChildren: false,
        actionUrl: '/wbase/wbase2050',
      },
    ],
  },
  {
    id: 'cat_300',
    code: '300',
    title: '發票統購',
    hasChildren: true,
    icon: 'Receipt',
    children: [
      {
        id: 'm_310',
        code: 'wbase3010',
        title: '購買地點',
        hasChildren: false,
        actionUrl: '/wbase/wbase3010',
      },
      {
        id: 'm_320',
        code: 'wbase3020',
        title: '預購統一發票輸入',
        hasChildren: false,
        actionUrl: '/wbase/wbase3020',
      },
      {
        id: 'm_330',
        code: 'wbase3030',
        title: '預購統一發票列印',
        hasChildren: false,
        actionUrl: '/wbase/wbase3030',
      },
      {
        id: 'm_340',
        code: 'GRP_340',
        title: '媒體/網路申購轉檔',
        hasChildren: true,
        children: [
          {
            id: 'm_341',
            code: 'wbase3041',
            title: '原媒體轉檔',
            hasChildren: false,
            actionUrl: '/wbase/wbase3041',
          },
          {
            id: 'm_342',
            code: 'wbase3042',
            title: '網路申購轉檔',
            hasChildren: false,
            actionUrl: '/wbase/wbase3042',
          },
        ],
      },
      {
        id: 'm_350',
        code: 'wbase3050',
        title: '購買統一發票清單列印',
        hasChildren: false,
        actionUrl: '/wbase/wbase3050',
      },
      {
        id: 'm_360',
        code: 'wbase3060',
        title: '統購發票字軌輸入',
        hasChildren: false,
        actionUrl: '/wbase/wbase3060',
      },
      {
        id: 'm_370',
        code: 'wbase3070',
        title: '刪除舊年度統購資料',
        hasChildren: false,
        actionUrl: '/wbase/wbase3070',
      },
    ],
  },
  {
    id: 'cat_400',
    code: '400',
    title: '操作設定',
    hasChildren: true,
    icon: 'Settings',
    children: [
      {
        id: 'm_410',
        code: 'GRP_410',
        title: '標準會計科目維護',
        hasChildren: true,
        children: [
          {
            id: 'm_411',
            code: 'wbase4011',
            title: '標準會計科目',
            hasChildren: false,
            actionUrl: '/wbase/wbase4011',
          },
          {
            id: 'm_412',
            code: 'wbase4012',
            title: '營造業會計科目',
            hasChildren: false,
            actionUrl: '/wbase/wbase4012',
          },
          {
            id: 'm_413',
            code: 'wbase4013',
            title: '建設業會計科目',
            hasChildren: false,
            actionUrl: '/wbase/wbase4013',
          },
          {
            id: 'm_414',
            code: 'wbase4014',
            title: '文教團體會計科目',
            hasChildren: false,
            actionUrl: '/wbase/wbase4014',
          },
          {
            id: 'm_415',
            code: 'wbase4015',
            title: '社會團體會計科目',
            hasChildren: false,
            actionUrl: '/wbase/wbase4015',
          },
          {
            id: 'm_416',
            code: 'wbase4016',
            title: '衛福團體會計科目',
            hasChildren: false,
            actionUrl: '/wbase/wbase4016',
          },
        ],
      },
      {
        id: 'm_420',
        code: 'wbase4020',
        title: '營業稅設定',
        hasChildren: false,
        actionUrl: '/wbase/wbase4020',
      },
      {
        id: 'm_430',
        code: 'wbase4030',
        title: '營業稅轉傳票設定',
        hasChildren: false,
        actionUrl: '/wbase/wbase4030',
      },
      {
        id: 'm_440',
        code: 'wbase4040',
        title: '媒體/期末存貨計算方式',
        hasChildren: false,
        actionUrl: '/wbase/wbase4040',
      },
      {
        id: 'm_450',
        code: 'wbase4050',
        title: '共用會計科目摘要',
        hasChildren: false,
        actionUrl: '/wbase/wbase4050',
      },
      {
        id: 'm_460',
        code: 'wbase4060',
        title: '共用參數設定',
        hasChildren: false,
        actionUrl: '/wbase/wbase4060',
      },
    ],
  },
  {
    id: 'cat_500',
    code: '500',
    title: '管理報表',
    hasChildren: true,
    icon: 'BarChart3',
    children: [
      {
        id: 'm_510',
        code: 'wbase5010',
        title: '客戶明細資料',
        hasChildren: false,
        actionUrl: '/wbase/wbase5010',
      },
      {
        id: 'm_520',
        code: 'wbase5020',
        title: '客戶郵遞標籤',
        hasChildren: false,
        actionUrl: '/wbase/wbase5020',
      },
      {
        id: 'm_530',
        code: 'wbase5030',
        title: '客戶登打統計表',
        hasChildren: false,
        actionUrl: '/wbase/wbase5030',
      },
      {
        id: 'm_540',
        code: 'wbase5040',
        title: '客戶營業狀況表',
        hasChildren: false,
        actionUrl: '/wbase/wbase5040',
      },
      {
        id: 'm_550',
        code: 'wbase5050',
        title: '財務狀況參考表',
        hasChildren: false,
        actionUrl: '/wbase/wbase5050',
      },
      {
        id: 'm_560',
        code: 'wbase5060',
        title: '委任書輸入列印',
        hasChildren: false,
        actionUrl: '/wbase/wbase5060',
      },
    ],
  },
  {
    id: 'cat_600',
    code: '600',
    title: '系統維護',
    hasChildren: true,
    icon: 'Wrench',
    children: [
      {
        id: 'm_610',
        code: 'wbase6010',
        title: '回存母版密碼變更',
        hasChildren: false,
        actionUrl: '/wbase/wbase6010',
      },
      {
        id: 'm_620',
        code: 'wbase6020',
        title: '轉檔列印密碼變更',
        hasChildren: false,
        actionUrl: '/wbase/wbase6020',
      },
      {
        id: 'm_630',
        code: 'wbase6030',
        title: '標準檔匯出匯入',
        hasChildren: false,
        actionUrl: '/wbase/wbase6030',
      },
    ],
  },
  {
    id: 'cat_800',
    code: '800',
    title: '系統講義',
    hasChildren: false,
    icon: 'BookOpen',
    actionUrl: '/wbase/help',
  },
  {
    id: 'cat_900',
    code: '900',
    title: '重新連線',
    hasChildren: false,
    icon: 'RefreshCw',
  },
  {
    id: 'cat_A00',
    code: 'A00',
    title: '結束離開',
    hasChildren: false,
    icon: 'LogOut',
  },
];
